package eu.daxiongmao.wordpress.db.dao;

import eu.daxiongmao.wordpress.db.model.WpUser;

import java.util.List;
import java.util.Optional;

/**
 * Custom DAO method with logic that is not auto-generated by Spring.
 * @version 1.0
 * @author Guillaume Diaz
 * @since 2021/01
 */
public interface WpUserDao {

    /**
     * To find an user by its email.
     * @param searchEmail email to retrieve
     * @return corresponding user or NULL
     */
    Optional<WpUser> findByEmail(String searchEmail);

    /**
     * To retrieve the list of blog authors.
     * IE: users that wrote articles
     * @return users that published articles. Empty list if no results are available.
     */
    List<WpUser> findAuthors();

}
